/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#a8e7c5",
        "inverse-primary": "#a9c7ff",
        "on-surface": "#191c1e",
        "error": "#ba1a1a",
        "surface": "#f9f9fd",
        "surface-container-highest": "#e2e2e6",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeef1",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002114",
        "inverse-on-surface": "#f0f0f4",
        "on-background": "#191c1e",
        "primary": "#00478d",
        "primary-fixed": "#d6e3ff",
        "surface-container-low": "#f3f3f7",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#bcece7",
        "outline": "#727783",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#2d6a4f",
        "inverse-surface": "#2e3133",
        "surface-container-high": "#e7e8eb",
        "primary-fixed-dim": "#a9c7ff",
        "surface-tint": "#005db6",
        "on-secondary-fixed-variant": "#1f4e4b",
        "background": "#f9f9fd",
        "primary-container": "#005eb8",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#0e5138",
        "on-primary-container": "#c8daff",
        "on-secondary-container": "#3d6a67",
        "surface-bright": "#f9f9fd",
        "outline-variant": "#c2c6d4",
        "surface-dim": "#d9dadd",
        "tertiary-fixed-dim": "#95d4b3",
        "on-surface-variant": "#424752",
        "surface-variant": "#e2e2e6",
        "secondary": "#396663",
        "secondary-fixed-dim": "#a0d0cb",
        "on-primary-fixed-variant": "#00468c",
        "tertiary-fixed": "#b1f0ce",
        "on-primary-fixed": "#001b3d",
        "secondary-container": "#b9e9e4",
        "tertiary": "#0f5238",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201e"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
